### ISSUE TITLE
Accesso negato

### ISSUE THREAD

**Issue by git-pushz** [lucamattiazzi/pastaporto#3]
Inizio con il ringraziarti perché mi è stato incredibilmente utile.
Di recente mi sono trovato a consigliarlo ad un amico ma ho notato che il bot dopo la prima risposta non continua la conversazione.
Andando a controllare l'url `https://www.passaportonline.poliziadistato.it/CittadinoAction.do?codop=resultRicercaRegistiProvincia&provincia=Cuneo` lo stato della risposta è 200 ma nell'html non ci sono informazioni sulle disponibilità ma soltanto un riquadro che dice "Accesso negato".
Non so se c'è qualche altra API per ottenere le disponibilità o meno, ma ci tenevo giusto a segnalarlo.

**Comment by filirnd** [comment]
Ciao Mi aggiungo anche io, il bot dopo aver selezionato la provincia non torna nessuna risposta (dopo aver inviato il messaggio "Fatto! .. ... .. Ecco lo stato attuale per questa provincia:"

**Comment by EZx92** [comment]
A

> Ciao Mi aggiungo anche io, il bot dopo aver selezionato la provincia non torna nessuna risposta (dopo aver inviato il messaggio "Fatto! .. ... .. Ecco lo stato attuale per questa provincia:"

Confermo... temo ci sia qualcosa che non lo fa più funzionare correttamente. Si riesce a fixare per caso?

**Comment by lucamattiazzi** [comment]
ci sto provando, ma al momento anche la pagina che usavo è dietro autenticazione spid, se riesco a risolvere butto su la versione nuova...

**Comment by lucamattiazzi** [comment]
sto più o meno risolvendo il problema, con sti ultimi commit
ho provato a mettere online questa versione, vedo se regge/funziona e metto a posto qualche roba nel frattempo
